/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function day1solveA(a: number, b: number, c: number): void;
export function day1solveB(a: number, b: number, c: number): void;
export function some_rust_string(a: number): void;
export function some_stuff(): number;
export function timed(a: number): number;
export function day7solveA(a: number, b: number, c: number): void;
export function day7solveB(a: number, b: number, c: number): void;
export function day5solveA(a: number, b: number, c: number): void;
export function day5solveB(a: number, b: number, c: number): void;
export function day3solveA(a: number, b: number, c: number): void;
export function day3solveB(a: number, b: number, c: number): void;
export function day9solveA(a: number, b: number, c: number): void;
export function day9solveB(a: number, b: number, c: number): void;
export function day2solveA(a: number, b: number, c: number): void;
export function day2solveB(a: number, b: number, c: number): void;
export function day6solveA(a: number, b: number, c: number): void;
export function day6solveB(a: number, b: number, c: number): void;
export function day4solveA(a: number, b: number, c: number): void;
export function day4solveB(a: number, b: number, c: number): void;
export function day8solveA(a: number, b: number, c: number): void;
export function day8solveB(a: number, b: number, c: number): void;
export function day10solveA(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export function __wbindgen_exn_store(a: number): void;
